version: "3"

services:
  cuda:
    build: 
      context: ./
      dockerfile: Dockerfile
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
       - ./mbd:/home/mbd
       - ../wind_disturbance:/home/wind_disturbance
       - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority:/home/admin/.Xauthority:rw 
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
